### ISSUE TITLE
Registeration page not working

### ISSUE THREAD

**Issue by kingstonwilliam** [FSSA-Project/TODO-App#11]
![Not Registering ](https://github.com/user-attachments/assets/e02658fb-0b7d-4a1b-b698-f4d40aedd7ef)
1)open Todo Registeration page 
2)Enter credential
3)click submit btn
4)error msg will occur
5)Try to clear this bug Asap
priority=High

**Comment by meganathan2003** [comment]
That's the problem of an apis you should wait for sometime to start the server this is not bug

**Comment by kingstonwilliam** [comment]
okay
