### ISSUE TITLE
User Validation Bug

### ISSUE THREAD

**Issue by kingstonwilliam** [FSSA-Project/TODO-App#12]
![UserBug](https://github.com/user-attachments/assets/6aa15bb7-be55-4e9f-bd69-0730d87547ac)
1)open Todo Sign Up page.
2)Enter Username more than 150 characters.
3)Click sign up button.
4)signing in with 150 characters.
5)Resolve this bug Asap.
Priority=Medium.

**Comment by meganathan2003** [comment]
@LogeshBharathi Could you please check this

**Comment by kingstonwilliam** [comment]
Bug Fixed
