### ISSUE TITLE
Password Accepting Null Value

### ISSUE THREAD

**Issue by kingstonwilliam** [FSSA-Project/TODO-App#14]
![EmptyPassword](https://github.com/user-attachments/assets/9bab4170-7f65-4b6a-a8b7-2907d1093236)
1)Navigate to the ToDo sign-up page.
2)Enter a null value in the password input field.
3)Ensure that null values are not accepted.
4)Address and resolve this issue as soon as possible.
Priority=High

**Comment by LogeshBharathi** [comment]
Dev Sign of this issue check with current build in Password Null Issue

**Comment by kingstonwilliam** [comment]
Bug fixed
