### ISSUE TITLE
Login Password Validation

### ISSUE THREAD

**Issue by kingstonwilliam** [FSSA-Project/TODO-App#15]
![LoginNullBug](https://github.com/user-attachments/assets/7a2a6505-2d3d-455e-8f89-49b8c69e9fdc)
1)Navigate to the ToDo Login
2)Enter a null value in the password input field.
3)Ensure that null values are not accepted.
4)Address and resolve this issue as soon as possible.
Priority=High

**Comment by LogeshBharathi** [comment]
Dev Sign of this issue check with current build

**Comment by kingstonwilliam** [comment]
Issues closed
