### ISSUE TITLE
UI bug

### ISSUE THREAD

**Issue by kingstonwilliam** [FSSA-Project/TODO-App#8]
![border bug](https://github.com/user-attachments/assets/f649dd61-8f33-4c04-9f67-d20a28338b25)
1)Enter todo Login .
2)UI design Border radius and front end Border Radius not matched.
3)Please fix the UI bug ASAP.
4)Priority-Low

**Comment by vigneshwarvj** [comment]
Dev sign off this issue. Check with current build.
Build Time: 29/07/24 - 07:42

**Comment by meganathan2003** [comment]
This issued has been fixed and Verfied in current build website
