### ISSUE TITLE
Logo Bugs

### ISSUE THREAD

**Issue by kingstonwilliam** [FSSA-Project/TODO-App#9]
![Google Logo bugs](https://github.com/user-attachments/assets/2b10275a-576c-483b-a941-934390e0d280)
1)Enter Todo app site
2)Front end google logo and Ui design google logo not matched 
3)Priority-Low

**Comment by vigneshwarvj** [comment]
Dev sign off this issue. Check with current build.
Build Time: 29/07/24 - 07:42

**Comment by meganathan2003** [comment]
This issue has been Fixed
